name: commit-to-repo
on:
  workflow_dispatch:
    inputs:
      branch_name:
        required: true
        type: string


jobs:
  commit-to-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create-branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ inputs.branch_name }}
      - name: create-file
        run: touch test-file
      - name: push
        env:
          branch_name: ${{ inputs.branch_name }}
        run: |
          git config --global user.name "Dome"
          git config --global user.email "dome.email"
          git add .
          git commit -m "test commit"
          git push -u origin $branch_name
