name: commit-to-repo
on:
  workflow_dispatch:
    inputs:
      dir_name:
        required: true
        type: string
      branch_name:
        required: true
        type: string
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create new branch
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git remote -v
          git branch --set-upstream-to=origin/${{ branch_name }} ${{ branch_name }}
          git checkout ${{ branch_name }}
      - name: Create report file
        run: touch ${{ inputs.dir_name }}
      - name: Commit report
        run: |
          git add .
          git commit -m "Automated report"
          git push
