name: test-output

on:
  workflow_dispatch:
    inputs:
      file_type:
        required: true
        type: choice
        options:
          - json
          - xml
          - custom



jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: yield-output
        id: get_output
        run: echo "my_output=some_output" >> "$GITHUB_OUTPUT"
      - name: get-output
        env:
          the_output: ${{ steps.get_output.outputs.my_output }}
        run: echo "The output is $the_output"
      - name: input-choice
        env:
          MY_INPUT: ${{ inputs.file_type }}
          other_var: value
        run: |
          echo "File type is $MY_INPUT"
          echo "Other var is $other_var"
