# This is a basic workflow to help you get started with Actions

name: push-to-repo

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: push-to-repo
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
  
          git clone https://loerinczy:$TOKEN@github.com/loerinczy/databricks_demo # This works
  
          cd databricks_demo
          git config user.name "user"
          git config user.email "dev@example.com"
  
          git checkout -b test-branch
  
          touch new-file.sh
          git add new-file.sh
          git commit -m "Add new file"
  
          git remote -v # Prints:
          # origin ***github.com/owner/my-repo.git (fetch)
          # origin ***github.com/owner/my-repo.git (push)
  
          git push --set-upstream origin test-branch # This does not work
          git push --set-upstream https://loerinczy:$TOKEN@github.com/loerinczy/databricks_demo test-branch
