name: steps-cwd

on:
  workflow_dispatch:


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: make dir
        run: |
          mkdir test_dir
          cd test_dir
          echo $PWD
